import uuid
from datetime import datetime

from sqlalchemy import String, Float, DateTime, Integer, Text, ForeignKey, JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class MatchAnalysis(Base):
    """Match analysis generated by AI."""
    
    __tablename__ = "match_analyses"
    
    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(
        String(36),
        ForeignKey("users.id"),
        index=True
    )
    
    # Match info from API-Football
    fixture_id: Mapped[int] = mapped_column(Integer, index=True)
    home_team: Mapped[str] = mapped_column(String(255))
    away_team: Mapped[str] = mapped_column(String(255))
    home_team_id: Mapped[int] = mapped_column(Integer)
    away_team_id: Mapped[int] = mapped_column(Integer)
    league_id: Mapped[int] = mapped_column(Integer)
    league_name: Mapped[str] = mapped_column(String(255), default="")
    match_date: Mapped[datetime] = mapped_column(DateTime)
    
    # AI Predictions
    prediction_home: Mapped[float] = mapped_column(Float)  # Probability 0-1
    prediction_draw: Mapped[float] = mapped_column(Float)
    prediction_away: Mapped[float] = mapped_column(Float)
    predicted_outcome: Mapped[str] = mapped_column(String(5))  # "1", "X", "2"
    confidence_score: Mapped[float] = mapped_column(Float)
    
    # Generated content
    summary: Mapped[str] = mapped_column(Text)
    key_factors: Mapped[list] = mapped_column(JSON, default=list)
    scenarios: Mapped[list] = mapped_column(JSON, default=list)
    
    # Data snapshot
    statistics_snapshot: Mapped[dict] = mapped_column(JSON, default=dict)
    news_context: Mapped[list] = mapped_column(JSON, default=list)
    value_bet: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    
    # Result (after match)
    actual_result: Mapped[str | None] = mapped_column(String(5), nullable=True)
    was_correct: Mapped[bool | None] = mapped_column(nullable=True)
    
    # Metadata
    created_at: Mapped[datetime] = mapped_column(
        DateTime,
        default=datetime.utcnow
    )

    # Relationships
    user: Mapped["User"] = relationship("User", back_populates="analyses")
    chat_messages: Mapped[list["ChatMessage"]] = relationship(
        "ChatMessage", 
        back_populates="analysis",
        cascade="all, delete-orphan"
    )
