"""Add ai_analysis to Coupon

Revision ID: 02397a2fb688
Revises: f8499b64ffc2
Create Date: 2025-12-27 10:57:22.901238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02397a2fb688'
down_revision: Union[str, None] = 'f8499b64ffc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupons', sa.Column('ai_analysis', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupons', 'ai_analysis')
    # ### end Alembic commands ###
