"""add_payment_method_to_users

Revision ID: 10a24c5a209e
Revises: a3b2c1d4e5f6
Create Date: 2025-12-27 16:38:08.142947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a24c5a209e'
down_revision: Union[str, None] = 'a3b2c1d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_analyses', sa.Column('value_bet', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('payment_method', sa.String(length=20), nullable=True, comment='stripe or moneroo - used to determine renewal behavior'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payment_method')
    op.drop_column('match_analyses', 'value_bet')
    # ### end Alembic commands ###
