"""add_team_logos_to_analysis

Revision ID: 319ed20f207a
Revises: 10a24c5a209e
Create Date: 2025-12-30 14:37:03.634238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319ed20f207a'
down_revision: Union[str, None] = '10a24c5a209e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_analyses', sa.Column('home_team_logo', sa.String(length=255), nullable=True))
    op.add_column('match_analyses', sa.Column('away_team_logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_analyses', 'away_team_logo')
    op.drop_column('match_analyses', 'home_team_logo')
    # ### end Alembic commands ###
